workflow:
  rules:
    - when: always

include:
  - local: ".gitlab/ci-${CI_COMMIT_REF_NAME}.yaml"
    rules:
      - if: '$CI_COMMIT_REF_NAME == "dev" || $CI_COMMIT_REF_NAME == "qa" || $CI_COMMIT_REF_NAME == "main"'
        exists:
          - ".gitlab/ci-${CI_COMMIT_REF_NAME}.yaml"

  - local: ".gitlab/ci-${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}.yaml"
    rules:
      - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
        exists:
          - ".gitlab/ci-${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}.yaml"

  - local: ".gitlab/ci-default.yaml"
    rules:
      - if: '$CI_COMMIT_REF_NAME != "dev" && $CI_COMMIT_REF_NAME != "qa" && $CI_COMMIT_REF_NAME != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"'
        exists:
          - ".gitlab/ci-default.yaml"

  - local: ".gitlab/ci-default.yaml"
    rules:
      - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "dev" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "qa" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'
        exists:
          - ".gitlab/ci-default.yaml"